### ISSUE TITLE
jsc：r174650 has "duplicate entry: javax/annotation/Nullable.class" when react android 0.15.0

### ISSUE THREAD

**Issue by yipengmu** [facebook/android-jsc#11] opened 2015-12-10 13:13 UTC
org.webkit.android-jsc.version=r174650

a problem attach to me when i use react native android 0.15.0:

duplicate entry: javax/annotation/Nullable.class

in abjectively case  , another maven GAV also has Nullable which the package is also javax.annotation. 
even  i can exclude an dependence a GAV ,bug i can't exclude all the files in an exist package,opps!
 
seem to https://github.com/johncarl81/parceler/issues/13

can @kmagiera @mkonicek help me and tell me  how to sovle it.

https://github.com/yipengmu/react-native-android-lession/blob/master/pics/jsc-bug.png
![jsc-annotation-bug](https://github.com/yipengmu/react-native-android-lession/blob/master/pics/jsc-bug.png)

**Comment by kmagiera** [comment] 2015-12-10 19:46
Duplicate of #10

**Closed by kmagiera** 2015-12-10 19:46 UTC
